name: Go

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        go: ["1.20", "1.21"]
    runs-on: ubuntu-latest
    container: golang:${{ matrix.go }}-bookworm
    steps:
    - run: go install golang.org/x/tools/cmd/goimports@latest
    - run: go install golang.org/x/lint/golint@latest
    - uses: actions/checkout@v1
    - run: ./gotest.sh
